services:
  backend:
    build: ./backend
    container_name: ts_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install --upgrade pip &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
  
  frontend:
    build: ./frontend
    container_name: ts_frontend
    restart: always
    ports:
      - "3000:80"

    depends_on:
      - backend